name: Github actions demo for Flutter

on:
  push:
    branches:
      - main

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: create assets
        run: |
          mkdir assets
      - name: create assets/strings.txt
        run: |
          echo "$STRINGS_BASE64" | base64 -d > assets/strings.txt
        env:
          STRINGS_BASE64: ${{ secrets.STRINGS_BASE64 }}
      - name: cat assets/strings.txt
        run: |
          cat assets/strings.txt
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Fetches and resolves project dependencies 
        run: flutter pub get
      - name: Run tests 
        run: flutter test
