name: Github actions demo for Flutter # ワークフローの名前

on:
  push:
    branches:
      - main # mainブランチにpushした時にワークフローが実行

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code # STEP1: レポジトリのコードを取得
        uses: actions/checkout@v4
      - name: Set up Flutter # STEP2: Flutterをインストール
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Fetches and resolves project dependencies # STEP3: 「flutter pub get」を実行
        run: flutter pub get
      - name: Run tests # STEP4: テストを実行
        run: flutter test
